// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $admin_visits from "./routes/admin/visits.tsx";
import * as $index from "./routes/index.tsx";
import * as $scratch_index from "./routes/scratch/index.tsx";
import * as $scratch_snake from "./routes/scratch/snake.tsx";
import * as $LocalTime from "./islands/LocalTime.tsx";
import * as $Nav_Hamburger from "./islands/Nav/Hamburger.tsx";
import * as $Nav_Mobile from "./islands/Nav/Mobile.tsx";
import * as $Nav_index from "./islands/Nav/index.tsx";
import * as $Nav_links from "./islands/Nav/links.ts";
import * as $SnekVG_Message from "./islands/SnekVG/Message.tsx";
import * as $SnekVG_index from "./islands/SnekVG/index.tsx";
import * as $SnekVG_utils from "./islands/SnekVG/utils.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/admin/visits.tsx": $admin_visits,
    "./routes/index.tsx": $index,
    "./routes/scratch/index.tsx": $scratch_index,
    "./routes/scratch/snake.tsx": $scratch_snake,
  },
  islands: {
    "./islands/LocalTime.tsx": $LocalTime,
    "./islands/Nav/Hamburger.tsx": $Nav_Hamburger,
    "./islands/Nav/Mobile.tsx": $Nav_Mobile,
    "./islands/Nav/index.tsx": $Nav_index,
    "./islands/Nav/links.ts": $Nav_links,
    "./islands/SnekVG/Message.tsx": $SnekVG_Message,
    "./islands/SnekVG/index.tsx": $SnekVG_index,
    "./islands/SnekVG/utils.ts": $SnekVG_utils,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
